version: '3'

services:
  
  web-app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      mongodb:
        condition: service_started

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - data-mongodb:/data/db
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    depends_on:
      mongodb:
        condition: service_started

volumes:
  data-mongodb:
    driver: local